`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 10/10/2026 09:00:00 PM
// Design Name: 
// Module Name: plant_pkg.sv
// Project Name: Time_Predictable_TTA
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

// GENERATED by `py -m host.plant_model.gen_sv` from host/plant_model/model.py. Do not edit.
// Regenerate after changing the plant; tests/test_plant.py fails if this file is stale.
//
// DC motor, ZOH at PLANT_STEP cycles (host/plant_model/README.md). States in Q.FP,
// coefficients in Q.FC, every update rounded half up:
//   theta' = theta + round((C01 omega + CU0 u + CT0 tau) / 2^FC)
//   omega' =         round((C11 omega + CU1 u + CT1 tau) / 2^FC)
// theta in encoder counts, omega in counts per plant step, u = pwm_cmd LSB,
// tau = load torque in units of 1e-6 N m.

/* verilator lint_off UNUSEDPARAM */
package plant_pkg;

  localparam int PLANT_STEP = 10000;   // cycles between plant steps (100 us)
  localparam int FP = 16;              // state fraction bits
  localparam int FC = 24;              // coefficient fraction bits

  // hardware-in-the-loop environment (host/hil/env.py)
  localparam int PLANT_PHASE = 0;      // plant steps when now mod PLANT_STEP == PLANT_PHASE
  localparam int LOAD_TAU    = 10000;  // load torque, 1e-6 N m
  localparam int LOAD_PERIOD = 100000000;
  localparam int LOAD_ON     = 40000000;   // load during [LOAD_ON, LOAD_OFF) of every LOAD_PERIOD
  localparam int LOAD_OFF    = 50000000;

  localparam logic signed [63:0] C01 = 64'sd16727634;
  localparam logic signed [63:0] C11 = 64'sd16678149;
  localparam logic signed [63:0] CU0 = 64'sd44489715;
  localparam logic signed [63:0] CU1 = 64'sd88891688;
  localparam logic signed [63:0] CT0 = -64'sd1107913;
  localparam logic signed [63:0] CT1 = -64'sd2213641;

endpackage
/* verilator lint_on UNUSEDPARAM */
