`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 10/06/2026 07:17:58 PM
// Design Name: 
// Module Name: tta_pkg.sv
// Project Name: Time_Predictable_TTA
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////

// GENERATED by `py -m host.common.gen_sv` from host/common/spec.py. Do not edit.
// Regenerate after changing spec.py; tests/test_gen_sv.py fails if this file is stale.

// A package exports constants that a given design may not use.
/* verilator lint_off UNUSEDPARAM */
package tta_pkg;

  localparam string SPEC_ID = "phase0-frozen-2026-10-02";

  // ---- instruction format (isa.md sec. 1)
  localparam int WORD_W   = 32;
  localparam int DST_LSB  = 24;
  localparam int IMM_BIT  = 23;
  localparam int IMM_W    = 23;

  // ---- timing constants (timing_model.md sec. 1)
  localparam int T_D = 1;  // wake delay after a timing move
  localparam int T_P = 2;  // bubbles per taken control transfer
  localparam int T_H = 2;  // bubbles before the first handler move
  localparam int T_R = 2;  // cycle of the first move after reset

  // ---- implementation parameters
  localparam int IMEM_WORDS            = 4096;
  localparam int DMEM_WORDS            = 4096;
  localparam int TELEM_FIFO_WORDS      = 64;
  localparam int TELEM_CYCLES_PER_WORD = 1320;

  // ---- port IDs (isa.md sec. 2)
  typedef logic [7:0] port_id_t;
  localparam port_id_t P_R0            = 8'h10;
  localparam port_id_t P_R1            = 8'h11;
  localparam port_id_t P_R2            = 8'h12;
  localparam port_id_t P_R3            = 8'h13;
  localparam port_id_t P_R4            = 8'h14;
  localparam port_id_t P_R5            = 8'h15;
  localparam port_id_t P_R6            = 8'h16;
  localparam port_id_t P_R7            = 8'h17;
  localparam port_id_t P_R8            = 8'h18;
  localparam port_id_t P_R9            = 8'h19;
  localparam port_id_t P_R10           = 8'h1A;
  localparam port_id_t P_R11           = 8'h1B;
  localparam port_id_t P_R12           = 8'h1C;
  localparam port_id_t P_R13           = 8'h1D;
  localparam port_id_t P_R14           = 8'h1E;
  localparam port_id_t P_R15           = 8'h1F;
  localparam port_id_t P_ALU_A         = 8'h20;
  localparam port_id_t P_ALU_OP        = 8'h21;
  localparam port_id_t P_ALU_T_B       = 8'h22;
  localparam port_id_t P_ALU_OUT       = 8'h23;
  localparam port_id_t P_MUL_A         = 8'h30;
  localparam port_id_t P_MUL_T_B       = 8'h31;
  localparam port_id_t P_MUL_OUT       = 8'h32;
  localparam port_id_t P_CMP_A         = 8'h40;
  localparam port_id_t P_CMP_T_B       = 8'h41;
  localparam port_id_t P_CMP_EQ        = 8'h42;
  localparam port_id_t P_CMP_LT        = 8'h43;
  localparam port_id_t P_CMP_LTU       = 8'h44;
  localparam port_id_t P_PC_COND       = 8'h50;
  localparam port_id_t P_PC_T_JUMP     = 8'h51;
  localparam port_id_t P_PC_T_JZ       = 8'h52;
  localparam port_id_t P_PC_T_JNZ      = 8'h53;
  localparam port_id_t P_PC_T_CALL     = 8'h54;
  localparam port_id_t P_PC_LINK       = 8'h55;
  localparam port_id_t P_MEM_DATA_IN   = 8'h60;
  localparam port_id_t P_MEM_T_LOAD    = 8'h61;
  localparam port_id_t P_MEM_T_STORE   = 8'h62;
  localparam port_id_t P_MEM_DATA_OUT  = 8'h63;
  localparam port_id_t P_TMR_T_SYNC    = 8'h70;
  localparam port_id_t P_TMR_T_ADVANCE = 8'h71;
  localparam port_id_t P_TMR_T_WAIT    = 8'h72;
  localparam port_id_t P_TMR_T_ARM     = 8'h73;
  localparam port_id_t P_TMR_T_CLEAR   = 8'h74;
  localparam port_id_t P_TMR_ELAPSED   = 8'h75;
  localparam port_id_t P_TMR_FLAGS     = 8'h76;
  localparam port_id_t P_TRAP_HANDLER  = 8'h80;
  localparam port_id_t P_TRAP_CAUSE    = 8'h81;
  localparam port_id_t P_TRAP_EPC      = 8'h82;
  localparam port_id_t P_TRAP_T_HALT   = 8'h83;
  localparam port_id_t P_IO_ENCODER    = 8'h90;
  localparam port_id_t P_IO_PWM_CMD    = 8'h91;
  localparam port_id_t P_TELEM_T_PUSH  = 8'hA0;
  localparam port_id_t P_TELEM_DROPS   = 8'hA1;
  localparam port_id_t P_NULL          = 8'hFF;

  // ---- FU output latencies L (timing_model.md R2)
  localparam int LAT_ALU_OUT       = 1;
  localparam int LAT_MUL_OUT       = 2;
  localparam int LAT_CMP_EQ        = 1;
  localparam int LAT_CMP_LT        = 1;
  localparam int LAT_CMP_LTU       = 1;
  localparam int LAT_MEM_DATA_OUT  = 1;

  // ---- ALU opcodes (isa.md sec. 4)
  typedef enum logic [3:0] {
    ALU_ADD = 4'd0,
    ALU_SUB = 4'd1,
    ALU_AND = 4'd2,
    ALU_OR = 4'd3,
    ALU_XOR = 4'd4,
    ALU_SHL = 4'd5,
    ALU_SHR = 4'd6,
    ALU_SRA = 4'd7,
    ALU_MIN = 4'd8,
    ALU_MAX = 4'd9
  } alu_op_e;
  localparam int ALU_OP_MAX = 9;

  // ---- trap causes (isa.md sec. 9)
  typedef enum logic [2:0] {
    CAUSE_NONE = 3'd0,
    CAUSE_DEADLINE = 3'd1,
    CAUSE_ILLEGAL_PORT = 3'd2,
    CAUSE_ILLEGAL_ALU_OP = 3'd3,
    CAUSE_DATA_ADDR = 3'd4,
    CAUSE_JUMP_TARGET = 3'd5
  } trap_cause_e;

  // ---- tmr.flags bits (isa.md sec. 7)
  localparam int FLAG_LATE = 0;
  localparam int FLAG_ARMED = 1;
  localparam int FLAG_TRAPPED = 2;

  // ---- port access (isa.md sec. 2): IDs not listed are illegal
  function automatic logic port_readable(port_id_t id);
    case (id)
      P_R0: return 1'b1;
      P_R1: return 1'b1;
      P_R2: return 1'b1;
      P_R3: return 1'b1;
      P_R4: return 1'b1;
      P_R5: return 1'b1;
      P_R6: return 1'b1;
      P_R7: return 1'b1;
      P_R8: return 1'b1;
      P_R9: return 1'b1;
      P_R10: return 1'b1;
      P_R11: return 1'b1;
      P_R12: return 1'b1;
      P_R13: return 1'b1;
      P_R14: return 1'b1;
      P_R15: return 1'b1;
      P_ALU_OUT: return 1'b1;
      P_MUL_OUT: return 1'b1;
      P_CMP_EQ: return 1'b1;
      P_CMP_LT: return 1'b1;
      P_CMP_LTU: return 1'b1;
      P_PC_LINK: return 1'b1;
      P_MEM_DATA_OUT: return 1'b1;
      P_TMR_ELAPSED: return 1'b1;
      P_TMR_FLAGS: return 1'b1;
      P_TRAP_HANDLER: return 1'b1;
      P_TRAP_CAUSE: return 1'b1;
      P_TRAP_EPC: return 1'b1;
      P_IO_ENCODER: return 1'b1;
      P_TELEM_DROPS: return 1'b1;
      default: return 1'b0;
    endcase
  endfunction

  function automatic logic port_writable(port_id_t id);
    case (id)
      P_R0: return 1'b1;
      P_R1: return 1'b1;
      P_R2: return 1'b1;
      P_R3: return 1'b1;
      P_R4: return 1'b1;
      P_R5: return 1'b1;
      P_R6: return 1'b1;
      P_R7: return 1'b1;
      P_R8: return 1'b1;
      P_R9: return 1'b1;
      P_R10: return 1'b1;
      P_R11: return 1'b1;
      P_R12: return 1'b1;
      P_R13: return 1'b1;
      P_R14: return 1'b1;
      P_R15: return 1'b1;
      P_ALU_A: return 1'b1;
      P_ALU_OP: return 1'b1;
      P_ALU_T_B: return 1'b1;
      P_MUL_A: return 1'b1;
      P_MUL_T_B: return 1'b1;
      P_CMP_A: return 1'b1;
      P_CMP_T_B: return 1'b1;
      P_PC_COND: return 1'b1;
      P_PC_T_JUMP: return 1'b1;
      P_PC_T_JZ: return 1'b1;
      P_PC_T_JNZ: return 1'b1;
      P_PC_T_CALL: return 1'b1;
      P_PC_LINK: return 1'b1;
      P_MEM_DATA_IN: return 1'b1;
      P_MEM_T_LOAD: return 1'b1;
      P_MEM_T_STORE: return 1'b1;
      P_TMR_T_SYNC: return 1'b1;
      P_TMR_T_ADVANCE: return 1'b1;
      P_TMR_T_WAIT: return 1'b1;
      P_TMR_T_ARM: return 1'b1;
      P_TMR_T_CLEAR: return 1'b1;
      P_TRAP_HANDLER: return 1'b1;
      P_TRAP_T_HALT: return 1'b1;
      P_IO_PWM_CMD: return 1'b1;
      P_TELEM_T_PUSH: return 1'b1;
      P_NULL: return 1'b1;
      default: return 1'b0;
    endcase
  endfunction

endpackage
/* verilator lint_on UNUSEDPARAM */
