"""Generate plant_pkg.sv (Vivado project sources) from the Python plant model,
so the RTL plant uses the very coefficients FixedPlant uses.

    py -m host.plant_model.gen_sv            write the file
    py -m host.plant_model.gen_sv --check    exit 1 if the committed file is stale

tests/test_plant.py fails if the committed file drifts from model.py.
"""
import argparse
import sys
from pathlib import Path

from . import model as m

OUT = (Path(__file__).resolve().parents[2] / "Time_Predictable_TTA.srcs" / "sources_1" / "new"
       / "plant_pkg.sv")

HEADER = [
    '`timescale 1ns / 1ps',
    '//////////////////////////////////////////////////////////////////////////////////',
    '// Company: ',
    '// Engineer: ',
    '// ',
    '// Create Date: 10/10/2026 09:00:00 PM',
    '// Design Name: ',
    '// Module Name: plant_pkg.sv',
    '// Project Name: Time_Predictable_TTA',
    '// Target Devices: ',
    '// Tool Versions: ',
    '// Description: ',
    '// ',
    '// Dependencies: ',
    '// ',
    '// Revision:',
    '// Revision 0.01 - File Created',
    '// Additional Comments:',
    '// ',
    '//////////////////////////////////////////////////////////////////////////////////',
]


def sv64(v):
    return f"-64'sd{-v}" if v < 0 else f"64'sd{v}"


def generate():
    from host.hil import env              # the HIL environment around the plant
    p = m.FixedPlant()
    w = list(HEADER)
    add = w.append
    add("")
    add("// GENERATED by `py -m host.plant_model.gen_sv` from host/plant_model/model.py. Do not edit.")
    add("// Regenerate after changing the plant; tests/test_plant.py fails if this file is stale.")
    add("//")
    add("// DC motor, ZOH at PLANT_STEP cycles (host/plant_model/README.md). States in Q.FP,")
    add("// coefficients in Q.FC, every update rounded half up:")
    add("//   theta' = theta + round((C01 omega + CU0 u + CT0 tau) / 2^FC)")
    add("//   omega' =         round((C11 omega + CU1 u + CT1 tau) / 2^FC)")
    add("// theta in encoder counts, omega in counts per plant step, u = pwm_cmd LSB,")
    add("// tau = load torque in units of 1e-6 N m.")
    add("")
    add("/* verilator lint_off UNUSEDPARAM */")
    add("package plant_pkg;")
    add("")
    add(f"  localparam int PLANT_STEP = {m.PLANT_STEP};   // cycles between plant steps (100 us)")
    add(f"  localparam int FP = {m.FP};              // state fraction bits")
    add(f"  localparam int FC = {m.FC};              // coefficient fraction bits")
    add("")
    add("  // hardware-in-the-loop environment (host/hil/env.py)")
    add(f"  localparam int PLANT_PHASE = {env.PLANT_PHASE};      // plant steps when now mod PLANT_STEP == PLANT_PHASE")
    add(f"  localparam int LOAD_TAU    = {env.LOAD_TAU};  // load torque, 1e-6 N m")
    add(f"  localparam int LOAD_PERIOD = {env.LOAD_PERIOD};")
    add(f"  localparam int LOAD_ON     = {env.LOAD_ON};   // load during [LOAD_ON, LOAD_OFF) of every LOAD_PERIOD")
    add(f"  localparam int LOAD_OFF    = {env.LOAD_OFF};")
    add("")
    for name, v in (("C01", p.c01), ("C11", p.c11), ("CU0", p.cu[0]), ("CU1", p.cu[1]),
                    ("CT0", p.ct[0]), ("CT1", p.ct[1])):
        add(f"  localparam logic signed [63:0] {name} = {sv64(v)};")
    add("")
    add("endpackage")
    add("/* verilator lint_on UNUSEDPARAM */")
    return "\n".join(w) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(prog="py -m host.plant_model.gen_sv")
    ap.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = ap.parse_args(argv)
    text = generate()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if args.check:
        if current != text:
            print(f"{OUT} is stale; run py -m host.plant_model.gen_sv", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
