"""Generate the Phase 5 control programs from one template.

    py -m host.hil.programs        rewrite programs/control.tta, control_trap.tta, control_sw.tta

control.tta       PID position control of the DC motor plant at 1 kHz
control_trap.tta  the same, but period TRAP_K runs past its deadline on purpose
control_sw.tta    the same PID, setpoint from io.din (switch mode, docs/io_interface.md)

The PID is host/plant_model FixedPID move for move (tests/test_hil.py checks
it against the model). Each period, following timing_model.md sec. 5 ex. 3:

    anchor + 1      sense       io.encoder -> r1
    anchor + 1001   actuate     r7 -> io.pwm_cmd       (t_wait #ACT)
    deadline        anchor + DEADLINE, cleared right after actuating

and one telemetry record of 8 words:
    MAGIC, k, ref, encoder, pwm_cmd, elapsed at sense + 1, elapsed at actuate + 1, tmr.flags
A deadline trap halts (fail-stop): the handler sets pwm_cmd = 0 and sends
    TRAP_MAGIC, trap.cause, trap.epc, elapsed at its first move, k

control_sw.tta reads io.din right after sensing and takes the setpoint from
env.SP_TABLE[din & 3] by a table lookup (no branch, so the time does not depend
on din). Its record has 9 words:
    SW_MAGIC, k, din, ref, encoder, pwm_cmd, elapsed after the inputs, elapsed at actuate + 1, tmr.flags
The PID text is the same as control.tta; generate() derives the switch version
by replacing the setpoint and schedule parts, so the two cannot drift apart.
"""
import sys
from pathlib import Path

from host.plant_model import model as m

from . import env

ROOT = Path(__file__).resolve().parents[2]
OUT = {False: ROOT / "programs" / "control.tta", True: ROOT / "programs" / "control_trap.tta"}
OUT_SW = ROOT / "programs" / "control_sw.tta"

MAGIC = 0x4849_4C31             # "HIL1"
TRAP_MAGIC = 0x5452_4150        # "TRAP"
PERIOD = 100_000
ACT = 1_000
DEADLINE = 2_000
RECORD_WORDS = 8
SW_MAGIC = 0x4853_5731          # "HSW1"
SW_RECORD_WORDS = 9
DIN_AT = 2                      # control_sw.tta reads io.din at anchor + 2
TRAP_K = 50                     # control_trap.tta: the period that overruns
SLOW_ITER = 600                 # x 5 cycles: well past DEADLINE


def generate(trap=False, switch=False):
    assert not (trap and switch)
    w = []
    add = w.append
    add(f"; GENERATED by `py -m host.hil.programs` (host/hil/programs.py). Do not edit.")
    add(";")
    if switch:
        add("; Switch mode: the PID of control.tta, with the setpoint taken from io.din")
        add("; (din[1:0] -> SP_TABLE, committed with BTN0; din[2] is the load switch, logged only).")
        add(";   anchor + 1     sense    (io.encoder)")
        add(f";   anchor + {DIN_AT}     input    (io.din)")
        add(f";   anchor + {ACT + 1}  actuate  (io.pwm_cmd)")
        add(f";   anchor + {DEADLINE}  deadline")
        add("; Telemetry per period: SW_MAGIC, k, din, ref, encoder, pwm_cmd, elapsed after the")
        add(";   inputs, elapsed after actuate, tmr.flags   (host/hil/board.py --switch reads it)")
    elif trap:
        add("; Deadline trap test: the control task of control.tta, except that period")
        add(f"; TRAP_K = {TRAP_K} spins for about {SLOW_ITER * 5} cycles before t_wait, so the deadline")
        add("; at anchor + DEADLINE fires inside the spin. The handler sets pwm_cmd = 0,")
        add("; reports the trap and halts. The WCET tool reports this task OVER on purpose.")
    else:
        add("; Phase 5 control task: PID position control of the DC motor plant at 1 kHz,")
        add("; host/plant_model FixedPID move for move. The setpoint follows SCHEDULE.")
    if not switch:
        add(";   anchor + 1     sense    (io.encoder)")
        add(f";   anchor + {ACT + 1}  actuate  (io.pwm_cmd)")
        add(f";   anchor + {DEADLINE}  deadline")
        add(f"; Telemetry per period: MAGIC, k, ref, encoder, pwm_cmd, elapsed after sense,")
        add(";   elapsed after actuate, tmr.flags   (host/hil/board.py reads it)")
    add("")
    for k, v in (("PERIOD", PERIOD), ("ACT", ACT), ("DEADLINE", DEADLINE),
                 ("KPQ", m.KPQ), ("KDQ", m.KDQ), ("KIQ", m.KIQ), ("HALF", 1 << (m.SH - 1)),
                 ("SH", m.SH), ("ECLAMP", m.E_CLAMP), ("UMAX", m.U_MAX)):
        add(f".equ {k + ',':9} {v}")
    if trap:
        add(f".equ TRAP_K,   {TRAP_K}")
        add(f".equ SLOW,     {SLOW_ITER}")
    body = """
        #on_trap    -> trap.handler
        #sched      -> r12              ; r12 = schedule entry
        r12         -> mem.t_load
        mem.data_out -> r11             ; r11 = periods left in it
        #sched + 1  -> mem.t_load
        mem.data_out -> r10             ; r10 = setpoint
        #0          -> tmr.t_sync
@task control
loop:   #PERIOD     -> tmr.t_advance
        io.encoder  -> r1               ; sense: anchor + 1
        tmr.elapsed -> r14              ; anchor + 2
        #DEADLINE   -> tmr.t_arm
        r10         -> r13              ; setpoint of this period, for telemetry
        ; e = clamp(ref - enc, -ECLAMP, ECLAMP)
        #SUB        -> alu.op
        r10         -> alu.a
        r1          -> alu.t_b
        #MIN        -> alu.op
        alu.out     -> alu.a
        #ECLAMP     -> alu.t_b
        #MAX        -> alu.op
        alu.out     -> alu.a
        #-ECLAMP    -> alu.t_b
        alu.out     -> r2               ; e
        ; p = KPQ * e, d = KDQ * (enc - prev), prev = enc
        #KPQ        -> mul.a
        r2          -> mul.t_b
        #SUB        -> alu.op           ; fills the MUL latency slot
        mul.out     -> r3               ; p
        r1          -> alu.a
        r8          -> alu.t_b          ; enc - prev
        r1          -> r8               ; prev = enc
        #KDQ        -> mul.a
        alu.out     -> mul.t_b
        r3          -> alu.a            ; fills the MUL latency slot
        mul.out     -> alu.t_b          ; p - d
        #ADD        -> alu.op
        alu.out     -> alu.a
        r5          -> alu.t_b          ; + acc
        alu.out     -> alu.a
        #HALF       -> alu.t_b          ; round half up
        #SRA        -> alu.op
        alu.out     -> alu.a
        #SH         -> alu.t_b
        alu.out     -> r6               ; u before saturation
        #MIN        -> alu.op
        r6          -> alu.a
        #UMAX       -> alu.t_b
        #MAX        -> alu.op
        alu.out     -> alu.a
        #-UMAX      -> alu.t_b
        alu.out     -> r7               ; u
        ; anti-windup: integrate unless saturated with e pushing the same way (e * u > 0)
        r6          -> cmp.a
        r7          -> cmp.t_b
        cmp.eq      -> pc.cond
        #integ      -> pc.t_jnz         ; not saturated
        #0          -> cmp.a
        r7          -> cmp.t_b          ; 0 < u ?
        cmp.lt      -> pc.cond
        #u_neg      -> pc.t_jz
        r2          -> cmp.t_b          ; u > 0: hold if 0 < e
        cmp.lt      -> pc.cond
        #sched_up   -> pc.t_jnz
        #integ      -> pc.t_jump
u_neg:  r2          -> cmp.a            ; u < 0: hold if e < 0
        #0          -> cmp.t_b
        cmp.lt      -> pc.cond
        #sched_up   -> pc.t_jnz
integ:  #KIQ        -> mul.a
        r2          -> mul.t_b
        #ADD        -> alu.op           ; fills the MUL latency slot
        mul.out     -> alu.a
        r5          -> alu.t_b          ; acc + KIQ * e
        #MIN        -> alu.op
        alu.out     -> alu.a
        #amax       -> mem.t_load
        mem.data_out -> alu.t_b
        #MAX        -> alu.op
        alu.out     -> alu.a
        #amin       -> mem.t_load
        mem.data_out -> alu.t_b
        alu.out     -> r5               ; acc
        ; setpoint schedule: count this period, load the next entry when it runs out
sched_up: #ADD      -> alu.op
        r11         -> alu.a
        #-1         -> alu.t_b
        alu.out     -> r11
        r11         -> pc.cond
        #sched_ok   -> pc.t_jnz
        r12         -> alu.a
        #2          -> alu.t_b
        alu.out     -> r12
        r12         -> mem.t_load
        mem.data_out -> r11
        r11         -> pc.cond
        #sched_ld   -> pc.t_jnz
        #sched      -> r12              ; end of the table: start over
        r12         -> mem.t_load
        mem.data_out -> r11
sched_ld: r12       -> alu.a
        #1          -> alu.t_b
        alu.out     -> mem.t_load
        mem.data_out -> r10
sched_ok: nop"""
    add(_switch_body(body) if switch else body)
    if trap:
        add("""        ; control_trap.tta only: period TRAP_K overruns its deadline
        r9          -> cmp.a
        #TRAP_K     -> cmp.t_b
        cmp.eq      -> pc.cond
        #on_time    -> pc.t_jz
        #SLOW       -> r15
@loop_bound SLOW
spin:   r15         -> alu.a
        #-1         -> alu.t_b
        alu.out     -> r15
        r15         -> pc.cond
        #spin       -> pc.t_jnz
on_time: nop""")
    tail = """        #ACT        -> tmr.t_wait
        r7          -> io.pwm_cmd       ; actuate: anchor + ACT + 1
        tmr.elapsed -> r15              ; anchor + ACT + 2
        #0          -> tmr.t_clear
        #magic      -> mem.t_load
        mem.data_out -> telem.t_push
        r9          -> telem.t_push     ; k
        r13         -> telem.t_push     ; setpoint
        r1          -> telem.t_push     ; encoder
        r7          -> telem.t_push     ; pwm_cmd
        r14         -> telem.t_push     ; elapsed after sense
        r15         -> telem.t_push     ; elapsed after actuate
        tmr.flags   -> telem.t_push
        #ADD        -> alu.op
        r9          -> alu.a
        #1          -> alu.t_b
        alu.out     -> r9               ; k + 1
        #loop       -> pc.t_jump

; deadline trap: make the plant safe, report, stop (no return from a trap)
.func on_trap
        tmr.elapsed -> r15              ; first handler move: deadline + 1 + H
        #0          -> io.pwm_cmd
        #tmagic     -> mem.t_load
        mem.data_out -> telem.t_push
        trap.cause  -> telem.t_push
        trap.epc    -> telem.t_push
        r15         -> telem.t_push
        r9          -> telem.t_push
        #0          -> trap.t_halt
.endfunc

        .data"""
    if switch:
        tail = _replace_once(tail, """        r9          -> telem.t_push     ; k
        r13         -> telem.t_push     ; setpoint""", """        r9          -> telem.t_push     ; k
        r4          -> telem.t_push     ; din
        r13         -> telem.t_push     ; setpoint""")
        tail = _replace_once(tail, "r14         -> telem.t_push     ; elapsed after sense",
                             "r14         -> telem.t_push     ; elapsed after the inputs")
    add(tail)
    add(f"magic:  .word 0x{SW_MAGIC if switch else MAGIC:08X}")
    add(f"tmagic: .word 0x{TRAP_MAGIC:08X}")
    add(f"amax:   .word {m.ACC_MAX}")
    add(f"amin:   .word {-m.ACC_MAX}")
    if switch:
        add("sptab:  .word " + ", ".join(str(v) for v in env.SP_TABLE) + "   ; setpoint by din[1:0]")
    else:
        add("sched:                                  ; (periods, setpoint), 0 ends the table")
        for n, ref in env.SCHEDULE:
            add(f"        .word {n}, {ref}")
        add("        .word 0")
    return "\n".join(w) + "\n"


def _replace_once(text, old, new):
    assert text.count(old) == 1, old
    return text.replace(old, new)


# control_sw.tta: what replaces the setpoint part of the shared PID text
_SW_PROLOGUE = (
    """        #on_trap    -> trap.handler
        #sched      -> r12              ; r12 = schedule entry
        r12         -> mem.t_load
        mem.data_out -> r11             ; r11 = periods left in it
        #sched + 1  -> mem.t_load
        mem.data_out -> r10             ; r10 = setpoint
        #0          -> tmr.t_sync
@task control
loop:   #PERIOD     -> tmr.t_advance
        io.encoder  -> r1               ; sense: anchor + 1
        tmr.elapsed -> r14              ; anchor + 2
        #DEADLINE   -> tmr.t_arm
        r10         -> r13              ; setpoint of this period, for telemetry""",
    """        #on_trap    -> trap.handler
        #0          -> tmr.t_sync
@task control
loop:   #PERIOD     -> tmr.t_advance
        io.encoder  -> r1               ; sense: anchor + 1
        io.din      -> r4               ; input: anchor + 2
        tmr.elapsed -> r14              ; anchor + 3
        #DEADLINE   -> tmr.t_arm
        ; setpoint = SP_TABLE[din & 3], a lookup: the same moves for every din
        #AND        -> alu.op
        r4          -> alu.a
        #3          -> alu.t_b
        #ADD        -> alu.op
        alu.out     -> alu.a
        #sptab      -> alu.t_b
        alu.out     -> mem.t_load
        mem.data_out -> r10             ; setpoint
        r10         -> r13              ; setpoint of this period, for telemetry""")


def _switch_body(body):
    body = _replace_once(body, *_SW_PROLOGUE)
    start = body.index("        ; setpoint schedule: count this period")
    assert body.endswith("sched_ok: nop")
    return body[:start] + "sched_up: nop                   ; no schedule: the setpoint comes from io.din"


def main(argv=None):
    for trap, path in OUT.items():
        path.write_text(generate(trap), encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    OUT_SW.write_text(generate(switch=True), encoding="utf-8", newline="\n")
    print(f"wrote {OUT_SW.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
