"""Generate tta_pkg.sv (in the Vivado project sources) from spec.py so RTL never retypes a number.

    py -m host.common.gen_sv            write the file
    py -m host.common.gen_sv --check    exit 1 if the committed file is stale

The generated file is committed, so opening the RTL needs no Python. The test
suite (tests/test_gen_sv.py) fails if it drifts from spec.py.
"""
import argparse
import re
import sys
from pathlib import Path

from . import spec

OUT = (Path(__file__).resolve().parents[2] / "Time_Predictable_TTA.srcs" / "sources_1" / "new"
       / "tta_pkg.sv")


def sv_name(port_name):
    """'alu.t_b' -> 'P_ALU_T_B', 'r3' -> 'P_R3', 'null' -> 'P_NULL'."""
    return "P_" + re.sub(r"[^A-Za-z0-9]", "_", port_name).upper()


def generate():
    w = []
    add = w.append
    add("// GENERATED by `py -m host.common.gen_sv` from host/common/spec.py. Do not edit.")
    add("// Regenerate after changing spec.py; tests/test_gen_sv.py fails if this file is stale.")
    add("")
    add("// A package exports constants that a given design may not use.")
    add("/* verilator lint_off UNUSEDPARAM */")
    add("package tta_pkg;")
    add("")
    add(f'  localparam string SPEC_ID = "{spec.SPEC_ID}";')
    add("")
    add("  // ---- instruction format (isa.md sec. 1)")
    add(f"  localparam int WORD_W   = {spec.WORD_BITS};")
    add(f"  localparam int DST_LSB  = {spec.DST_SHIFT};")
    add(f"  localparam int IMM_BIT  = {spec.IMM_BIT};")
    add(f"  localparam int IMM_W    = {spec.IMM_BITS};")
    add("")
    add("  // ---- timing constants (timing_model.md sec. 1)")
    add(f"  localparam int T_D = {spec.D};  // wake delay after a timing move")
    add(f"  localparam int T_P = {spec.P};  // bubbles per taken control transfer")
    add(f"  localparam int T_H = {spec.H};  // bubbles before the first handler move")
    add(f"  localparam int T_R = {spec.R};  // cycle of the first move after reset")
    add("")
    add("  // ---- implementation parameters")
    add(f"  localparam int IMEM_WORDS            = {spec.IMEM_WORDS};")
    add(f"  localparam int DMEM_WORDS            = {spec.DMEM_WORDS};")
    add(f"  localparam int TELEM_FIFO_WORDS      = {spec.TELEM_FIFO_WORDS};")
    add(f"  localparam int TELEM_CYCLES_PER_WORD = {spec.TELEM_CYCLES_PER_WORD};")
    add("")
    add("  // ---- port IDs (isa.md sec. 2)")
    add("  typedef logic [7:0] port_id_t;")
    width = max(len(sv_name(p.name)) for p in spec.PORTS)
    for p in spec.PORTS:
        add(f"  localparam port_id_t {sv_name(p.name):<{width}} = 8'h{p.id:02X};")
    add("")
    add("  // ---- FU output latencies L (timing_model.md R2)")
    for p in spec.PORTS:
        if p.latency is not None:
            add(f"  localparam int LAT_{sv_name(p.name)[2:]:<{width - 2}} = {p.latency};")
    add("")
    add("  // ---- ALU opcodes (isa.md sec. 4)")
    add("  typedef enum logic [3:0] {")
    ops = list(spec.AluOp)
    for i, op in enumerate(ops):
        add(f"    ALU_{op.name} = 4'd{op.value}{',' if i < len(ops) - 1 else ''}")
    add("  } alu_op_e;")
    add(f"  localparam int ALU_OP_MAX = {max(spec.AluOp).value};")
    add("")
    add("  // ---- trap causes (isa.md sec. 9)")
    add("  typedef enum logic [2:0] {")
    causes = list(spec.TrapCause)
    for i, c in enumerate(causes):
        add(f"    CAUSE_{c.name} = 3'd{c.value}{',' if i < len(causes) - 1 else ''}")
    add("  } trap_cause_e;")
    add("")
    add("  // ---- tmr.flags bits (isa.md sec. 7)")
    for f in spec.TmrFlag:
        add(f"  localparam int FLAG_{f.name} = {f.value};")
    add("")
    add("  // ---- port access (isa.md sec. 2): IDs not listed are illegal")
    for fn, attr in (("port_readable", "readable"), ("port_writable", "writable")):
        add(f"  function automatic logic {fn}(port_id_t id);")
        add("    case (id)")
        ids = [p for p in spec.PORTS if getattr(p, attr)]
        for p in ids:
            add(f"      {sv_name(p.name)}: return 1'b1;")
        add("      default: return 1'b0;")
        add("    endcase")
        add("  endfunction")
        add("")
    add("endpackage")
    add("/* verilator lint_on UNUSEDPARAM */")
    return "\n".join(w) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(prog="py -m host.common.gen_sv")
    ap.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = ap.parse_args(argv)
    text = generate()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if args.check:
        if current != text:
            print(f"{OUT} is stale; run py -m host.common.gen_sv", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
